name: informa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  charts_flutter: ^0.12.0
  cloud_firestore: ^3.4.1
  confetti: ^0.7.0
  country_code_picker: ^2.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_database: ^9.0.20
  firebase_storage: ^10.2.4
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.0
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.1.0
  flutter_native_timezone: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.3
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^5.1.0
  http: ^0.13.3
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.1
  percent_indicator: ^4.2.2
  pinput: ^2.2.11
  provider: ^6.0.1
  rxdart: ^0.27.3
  share: ^2.0.4
  shared_preferences: ^2.0.7
  syncfusion_flutter_charts: ^20.2.40
  table_calendar: ^3.0.3
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/
    - assets/images/body_fat/
    - assets/icons/
    - assets/files/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: CairoRegular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
