import 'package:informa/models/meal.dart';

class SnacksList{
  static List<Meal> snacks = [
    Meal(
      id: '1000',
      name: 'واي بروتين',
      engName: 'Whey protein',
      protein: 25,
      fats: 1,
      carb: 2,
      calories: 117,
      serving: 1,
      unit: 'scoop',
      category: 'وجبات خفيفة',
      components: [
        '1 أسكوب واي بروتين'
      ],
    ),
    //Molten cakes
    Meal(
      id: '1001',
      name: 'كيكة منصهرة',
      engName: 'Molten cake',
      protein: 28,
      fats: 1,
      carb: 10,
      calories: 161,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '1 سكوب واي بروتين',
        'معلقة baking powder صغيرة',
        'سكر دايت - زي ما تحب',
        '120 جرام حليب خالي الدسم',
      ],
    ),
    Meal(
      id: '1002',
      name: 'بان كيك',
      engName: 'Pan cake',
      protein: 28,
      fats: 1,
      carb: 10,
      calories: 161,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '1 سكوب واي بروتين',
        'معلقة كاكاو صغيرة',
        'معلقة baking powder صغيرة',
        'سكر دايت - زي ما تحب',
        '80 جرام حليب خالي الدسم',
      ],
    ),
    Meal(
      id: '1003',
      name: 'صوص اللوتس',
      engName: 'Lotus sauce',
      protein: 28,
      fats: 1,
      carb: 10,
      calories: 161,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '1 سكوب واي بروتين',
        'معلقة قرفة صغيرة',
        'بسكوتة شاي واحدة',
        'سكر دايت - زي ما تحب',
        '40 جرام حليب خالي الدسم',
      ],
    ),
    //Fruity greek yog
    Meal(
      id: '1004',
      name: 'زبادي يوناني بالفراولة',
      engName: 'Greek yogurt with strawberry',
      protein: 16,
      fats: 1,
      carb: 17,
      calories: 141,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '180 جرام زبادي يوناني لايت',
        '150 جرام فروالة او 50 جرام موز او 125 جرام فروالة او 70 جرام مانجة او 85 جرام تفاح',
        'يمكن تحلية الذبادي بسكر دايت',
      ],
    ),
    // Meal(
    //   id: '1005',
    //   name: 'زبادي يوناني بالموز',
    //   engName: 'Greek yogurt with banana',
    //   protein: 16,
    //   fats: 1,
    //   carb: 17,
    //   calories: 141,
    //   serving: 1,
    //   components: [
    //     '180 جرام زبادي يوناني لايت',
    //     '50 جرام موز',
    //     'يمكن تحلية الذبادي بسكر دايت',
    //   ],
    // ),
    // Meal(
    //   id: '1006',
    //   name: 'زبادي يوناني بالخوخ',
    //   engName: 'Greek yogurt with peach',
    //   protein: 16,
    //   fats: 1,
    //   carb: 17,
    //   calories: 141,
    //   serving: 1,
    //   components: [
    //     '180 جرام زبادي يوناني لايت',
    //     '125 جرام فروالة',
    //     'يمكن تحلية الذبادي بسكر دايت',
    //   ],
    // ),
    // Meal(
    //   id: '1007',
    //   name: 'زبادي يوناني بالمانجو',
    //   engName: 'Greek yogurt with mango',
    //   protein: 16,
    //   fats: 1,
    //   carb: 17,
    //   calories: 141,
    //   serving: 1,
    //   components: [
    //     '180 جرام زبادي يوناني لايت',
    //     '70 جرام مانجة',
    //     'يمكن تحلية الذبادي بسكر دايت',
    //   ],
    // ),
    // Meal(
    //   id: '1008',
    //   name: 'زبادي يوناني بالتفاح',
    //   engName: 'Greek yogurt with apple',
    //   protein: 16,
    //   fats: 1,
    //   carb: 17,
    //   calories: 141,
    //   serving: 1,
    //   components: [
    //     '180 جرام زبادي يوناني لايت',
    //     '85 جرام تفاح',
    //     'يمكن تحلية الذبادي بسكر دايت',
    //   ],
    // ),
    //Super shake
    Meal(
      id: '1009',
      name: 'سوبر شيك',
      engName: 'Super shake',
      protein: 33,
      fats: 39,
      carb: 115,
      calories: 943,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '50 جرام شوفان',
        '120 جرام موز',
        'معلقتين كبار عسل',
        '100 جرام زبادي كامل الدسم',
        '150 جرام لبن كامل الدسم',
        '50 جرام زبدة فول سوداني',
        'معلقة صغيرة كاكاو',
      ],
    ),
    //Oatmeal
    Meal(
      id: '1010',
      name: 'شوفان',
      engName: 'Oatmeal',
      protein: 14,
      fats: 4,
      carb: 77,
      calories: 161,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '45 جرام شوفان',
        '100 جرام موز',
        'معلقة كبيرة عسل',
        '150 جرام لبن خالي الدسم',
      ],
    ),
    //Fruits
    Meal(
      id: '1011',
      name: '25 فاكهة',
      engName: 'Fruit 25',
      protein: 1,
      fats: 0,
      carb: 25,
      calories: 104,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '25 جرام من الفاكهة',
      ],
    ),
    Meal(
      id: '1012',
      name: '40 فاكهة',
      engName: 'Fruit 40',
      protein: 2,
      fats: 0,
      carb: 40,
      calories: 168,
      serving: 1,
      category: 'وجبات خفيفة',
      components: [
        '40 جرام من الفاكهة',
      ],
    ),
  ];
}