import 'package:informa/models/meal.dart';

class SupplementsList {
  static List<Meal> supplements = [
    Meal(
      id: '1',
      name: 'كرياتين',
      engName: 'Creatine',
      serving: 1,
      components: ['بعد التمرين (في ايام الراحة في اي وقت)'],
    ),
    Meal(
      id: '2',
      name: 'أوميجا-3',
      engName: 'Omega-3',
      serving: 1,
      components: ['بعد ثاني وجبة'],
    ),
    Meal(
      id: '3',
      name: 'Multi Vitamin',
      engName: 'Multi Vitamin',
      serving: 1,
      components: ['بعد أول وجبة'],
    ),
    Meal(
      id: '4',
      name: 'Pre-Workout',
      engName: 'Pre-Workout',
      serving: 1,
      components: ['قبل التمرين '],
    ),
    Meal(
      id: '5',
      name: 'فات برنر',
      engName: 'Fat Burner',
      serving: 1,
      components: [
        'قبل اول وجبة (في ايام الراحة في اي وقت)',
        'قبل التمرين بنصف ساعة',
      ],
    ),
    Meal(
      id: '6',
      name: 'Bcaa',
      engName: 'Bcaa',
      serving: 1,
      components: ['اثناء التمرين'],
    ),
    Meal(
      id: '7',
      name: 'Eaa',
      engName: 'Eaa',
      serving: 1,
      components: ['بعد التمرين'],
    ),
    Meal(
      id: '8',
      name: 'Glutamine',
      engName: 'Glutamine',
      serving: 1,
      components: ['بعد التمرين (في أيام الراحة في أي وقت في اليوم)'],
    ),
    Meal(
      id: '9',
      name: 'Zinc',
      engName: 'Zinc',
      serving: 1,
      components: ['ساعة قبل النوم'],
    ),
    Meal(
      id: '10',
      name: 'ZMA',
      engName: 'ZMA',
      serving: 1,
      components: ['ساعة قبل النوم'],
    ),
    Meal(
      id: '11',
      name: 'Magnesium ',
      engName: 'Magnesium ',
      serving: 1,
      components: ['ساعة قبل النوم'],
    ),
    Meal(
      id: '12',
      name: 'Vitamin-C',
      engName: 'Vitamin-C',
      serving: 1,
      components: ['بعد أول وجبة'],
    ),
    Meal(
      id: '13',
      name: 'Vitamin-D',
      engName: 'Vitamin-D',
      serving: 1,
      components: ['بعد أول وجبة'],
    ),
    Meal(
      id: '14',
      name: 'L-Carnitine',
      engName: 'L-Carnitine',
      serving: 1,
      components: [
        'قبل التمرين',
        'بعد التمرين',
      ],
    ),
    Meal(
      id: '15',
      name: 'Test booster',
      engName: 'Test booster',
      serving: 1,
      components: ['بعد أخر وجبة'],
    ),
    Meal(
      id: '16',
      name: 'Arginine ',
      engName: 'Arginine ',
      serving: 1,
      components: ['قبل التمرين'],
    ),
    Meal(
      id: '17',
      name: 'Citrulline ',
      engName: 'Citrulline ',
      serving: 1,
      components: ['قبل النوم'],
    ),
    Meal(
      id: '18',
      name: 'Melatonin',
      engName: 'Melatonin',
      serving: 1,
      components: ['ساعة قبل النوم'],
    ),
    Meal(
      id: '19',
      name: 'Collagen',
      engName: 'Collagen',
      serving: 1,
      components: ['بعد ثاني وجبة'],
    ),
  ];
}